name: CI
on:
  push

jobs:
  build:
    permissions:
      contents: write
    runs-on: windows-latest
    steps:
      - uses: actions/setup-node@v3
        with:
          node-version: 18
      - uses: actions/checkout@v3
      - name: Install esy
        run: npm install -g esy
      - name: Build project
        run: esy
      - uses: actions/upload-artifact@v3
        with:
          name: default-manifest
          path: ./default-manifest.o
      - name: Release
        uses: softprops/action-gh-release@v1
        if: startsWith(github.ref, 'refs/tags/')
        with:
          files: ./default-manifest.o

